<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SAMPATH" failures="18" tests="38" name="RestAssured_API" time="23.192" errors="0" timestamp="06 Feb 2022 10:35:25 GMT">
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="@BeforeClass DeleteEmpRecord" time="2.263">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record.DeleteEmpRecord(TC005_Delete_Employee_Record.java:32)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
... 30 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass DeleteEmpRecord -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="@AfterClass TearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass TearDown -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkContentEncoding" time="0.004"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkContentLength" time="0.0"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkContentType" time="0.0"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkResponseTime" time="0.0"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkServerType" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx]
at com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees.checkServerType(TC001_Get_All_Employees.java:88)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkStatusCode" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees.checkStatusCode(TC001_Get_All_Employees.java:44)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkStatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 429 Too Many Requests]
at com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees.checkStatusLine(TC001_Get_All_Employees.java:68)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="checkcookies" time="0.001"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC001_Get_All_Employees" name="getResponseBody" time="0.019"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record" name="checkContentEncoding" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [gzip] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [gzip] but found [null]
at com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record.checkContentEncoding(TC002_Get_Single_Employee_Record.java:95)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentEncoding -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record" name="checkContentType" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [text/html; charset=UTF-8] but found [application/json]">
      <![CDATA[java.lang.AssertionError: expected [text/html; charset=UTF-8] but found [application/json]
at com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record.checkContentType(TC002_Get_Single_Employee_Record.java:75)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record" name="checkResponseTime" time="0.001"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record" name="checkServerType" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx]
at com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record.checkServerType(TC002_Get_Single_Employee_Record.java:85)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record" name="checkStatusCode" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record.checkStatusCode(TC002_Get_Single_Employee_Record.java:42)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record" name="checkStatusLine" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 404 Not Found]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 404 Not Found]
at com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record.checkStatusLine(TC002_Get_Single_Employee_Record.java:65)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record" name="getResponseBody" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.RestAssuredAutomation.TestCases.TC002_Get_Single_Employee_Record.getResponseBody(TC002_Get_Single_Employee_Record.java:33)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getResponseBody -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="checkContentEncoding" time="0.002"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="checkContentLength" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record.checkContentLength(TC003_Post_Employee_Record.java:140)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLength -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="checkContentType" time="0.001"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="checkResponseTime" time="0.001"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="checkServerType" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx]
at com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record.checkServerType(TC003_Post_Employee_Record.java:116)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="checkStatusCode" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record.checkStatusCode(TC003_Post_Employee_Record.java:73)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="checkStatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 429 Too Many Requests]
at com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record.checkStatusLine(TC003_Post_Employee_Record.java:96)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record" name="getResponseBody" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.RestAssuredAutomation.TestCases.TC003_Post_Employee_Record.getResponseBody(TC003_Post_Employee_Record.java:62)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getResponseBody -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record" name="checkContentEncoding" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [gzip] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [gzip] but found [null]
at com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record.checkContentEncoding(TC004_Put_Employee_Record.java:119)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentEncoding -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record" name="checkContentType" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [text/html; charset=UTF-8] but found [application/json]">
      <![CDATA[java.lang.AssertionError: expected [text/html; charset=UTF-8] but found [application/json]
at com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record.checkContentType(TC004_Put_Employee_Record.java:99)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record" name="checkResponseTime" time="0.001"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record" name="checkServerType" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx]
at com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record.checkServerType(TC004_Put_Employee_Record.java:109)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record" name="checkStatusLine" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 200 OK]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 Ok] but found [HTTP/1.1 200 OK]
at com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record.checkStatusLine(TC004_Put_Employee_Record.java:89)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC004_Put_Employee_Record" name="getResponseBody" time="0.0"/>
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkContentEncoding" time="0.0">
    <skipped/>
  </testcase> <!-- checkContentEncoding -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkContentType" time="0.0">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkResponseBody" time="0.0">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkResponseTime" time="0.0">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkServerType" time="0.0">
    <skipped/>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkStatusCode" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkStatusLine" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatusLine -->
</testsuite> <!-- RestAssured_API -->
